services:
  db:
    image: postgres:17
    container_name: homenest-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: homenest
      POSTGRES_USER: homenest_user
      POSTGRES_PASSWORD: homenest_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: