# Generated by Django 5.2.17 on 2026-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_maintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='issue_image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/'),
        ),
    ]
