# Generated by Django 5.2.17 on 2026-09-30 06:41

from django.db import migrations, models


def resolve_completed_requests(apps, schema_editor):
    MaintenanceRequest = apps.get_model("properties", "MaintenanceRequest")
    MaintenanceRequest.objects.filter(status="COMPLETED").update(status="RESOLVED")


def restore_completed_requests(apps, schema_editor):
    MaintenanceRequest = apps.get_model("properties", "MaintenanceRequest")
    MaintenanceRequest.objects.filter(status="RESOLVED").update(status="COMPLETED")


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_maintenancerequest_issue_image'),
    ]

    operations = [
        migrations.RunPython(
            resolve_completed_requests,
            restore_completed_requests,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
