# Generated by Django 5.2.17 on 2026-09-30 07:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_existing_request_history(apps, schema_editor):
    MaintenanceRequest = apps.get_model("properties", "MaintenanceRequest")
    MaintenanceRequestHistory = apps.get_model(
        "properties",
        "MaintenanceRequestHistory",
    )
    history_entries = [
        MaintenanceRequestHistory(
            maintenance_request_id=maintenance_request.pk,
            status=maintenance_request.status,
            owner_note=maintenance_request.owner_note or "",
            updated_at=maintenance_request.updated_at,
        )
        for maintenance_request in MaintenanceRequest.objects.all().iterator()
    ]
    MaintenanceRequestHistory.objects.bulk_create(history_entries)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_maintenancerequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('owner_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='properties.maintenancerequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_request_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_at', 'pk'],
            },
        ),
        migrations.RunPython(
            create_existing_request_history,
            migrations.RunPython.noop,
        ),
    ]
